# Pandas — Reading, Selecting, and Filtering

Pandas is the core library for data manipulation in Python.  
This notebook covers how to load, explore, select, and filter data — the first steps in any real analysis.

**Topics covered:**
- DataFrame structure
- Building a DataFrame manually
- Column selection
- Row selection: `iloc` and `loc`
- Filtering with boolean masks
- Sorting
- Quick summaries: `value_counts`, `describe`
- Reading a real CSV file
- Real-world filtering scenarios

In [4]:
import pandas as pd

# Load the dataset
df = pd.read_csv("ybs_satis_verisi.csv")

# Look at the first 5 rows
df.head()

,siparis_id,musteri_id,sehir,kategori,urun,adet,birim_fiyat,indirim_orani,satis_kanali,odeme_yontemi,siparis_tarihi,teslimat_gun,memnuniyet_puani,iptal_edildi
0,100001,1130,Adana,Kozmetik,Parfüm,3,2356.70,0.20,Web,Havale/EFT,2025-03-21,3,3,0
1,100002,1474,Kocaeli,Ev-Yaşam,Nevresim,4,11270.01,0.05,Mobil,Kredi Kartı,2025-03-31,3,1,0
2,100003,3435,Kocaeli,Market,Çay,4,584.78,0.10,Mobil,Kapıda Ödeme,2025-06-12,1,4,0
3,100004,1034,Konya,Elektronik,Powerbank,2,17651.03,0.05,Web,Kapıda Ödeme,2025-02-28,4,4,0
4,100005,5911,Ankara,Elektronik,Powerbank,4,14371.14,0.05,Mağaza,Kredi Kartı,2025-08-19,4,5,0

## 1. Setup

In [5]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 120)

print("Pandas version:", pd.__version__)

Pandas version: 3.0.2

## 2. Building a DataFrame Manually

Before loading real data, let's understand the DataFrame structure  
by creating a small one from a dictionary.

In [6]:
data = {
    "order_id"      : [201, 202, 203, 204, 205],
    "city"          : ["Istanbul", "Ankara", "Istanbul", "Izmir", "Bursa"],
    "category"      : ["Electronics", "Clothing", "Market", "Electronics", "Market"],
    "quantity"      : [1, 2, 5, 1, 3],
    "unit_price"    : [15000, 900, 90, 42000, 150],
    "payment"       : ["Credit Card", "Bank Transfer", "EFT", "Credit Card", "Cash on Delivery"]
}

df = pd.DataFrame(data)
df

   order_id      city     category  quantity  unit_price           payment
0       201  Istanbul  Electronics         1       15000       Credit Card
1       202    Ankara     Clothing         2         900     Bank Transfer
2       203  Istanbul       Market         5          90               EFT
3       204     Izmir  Electronics         1       42000       Credit Card
4       205     Bursa       Market         3         150  Cash on Delivery

### 2.1 Basic DataFrame Info

In [7]:
print("Rows / Columns:", df.shape)
print("Columns:", list(df.columns))
df.info()

Rows / Columns: (5, 6)
Columns: ['order_id', 'city', 'category', 'quantity', 'unit_price', 'payment']
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5 non-null      int64
 1   city        5 non-null      str
 2   category    5 non-null      str
 3   quantity    5 non-null      int64
 4   unit_price  5 non-null      int64
 5   payment     5 non-null      str
dtypes: int64(3), str(3)
memory usage: 372.0 bytes

## 3. Column Selection

### 3.1 Single Column

In [8]:
df["city"]

0    Istanbul
1      Ankara
2    Istanbul
3       Izmir
4       Bursa
Name: city, dtype: str

### 3.2 Multiple Columns

In [9]:
df[["order_id", "category", "quantity", "unit_price"]]

   order_id     category  quantity  unit_price
0       201  Electronics         1       15000
1       202     Clothing         2         900
2       203       Market         5          90
3       204  Electronics         1       42000
4       205       Market         3         150

### 3.3 Creating a New Column

In [10]:
df["total_price"] = df["quantity"] * df["unit_price"]
df

   order_id      city     category  quantity  unit_price           payment  total_price
0       201  Istanbul  Electronics         1       15000       Credit Card        15000
1       202    Ankara     Clothing         2         900     Bank Transfer         1800
2       203  Istanbul       Market         5          90               EFT          450
3       204     Izmir  Electronics         1       42000       Credit Card        42000
4       205     Bursa       Market         3         150  Cash on Delivery          450

## 4. Row Selection: `iloc` and `loc`

### 4.1 `iloc` — by index position

In [11]:
df.iloc[0]        # first row

order_id               201
city              Istanbul
category       Electronics
quantity                 1
unit_price           15000
payment        Credit Card
total_price          15000
Name: 0, dtype: object

In [12]:
df.iloc[0:3]      # first 3 rows

   order_id      city     category  quantity  unit_price        payment  total_price
0       201  Istanbul  Electronics         1       15000    Credit Card        15000
1       202    Ankara     Clothing         2         900  Bank Transfer         1800
2       203  Istanbul       Market         5          90            EFT          450

### 4.2 `loc` — by label / condition

Our index is 0-based here, so `loc[0]` gives the first row.

In [13]:
df.loc[0]

order_id               201
city              Istanbul
category       Electronics
quantity                 1
unit_price           15000
payment        Credit Card
total_price          15000
Name: 0, dtype: object

## 5. Filtering (Boolean Mask)

### 5.1 Single city

In [14]:
df[df["city"] == "Istanbul"]

   order_id      city     category  quantity  unit_price      payment  total_price
0       201  Istanbul  Electronics         1       15000  Credit Card        15000
2       203  Istanbul       Market         5          90          EFT          450

### 5.2 Electronics with unit price above 20,000

In [15]:
df[(df["category"] == "Electronics") & (df["unit_price"] > 20000)]

   order_id   city     category  quantity  unit_price      payment  total_price
3       204  Izmir  Electronics         1       42000  Credit Card        42000

### 5.3 Multiple categories with `isin()`

In [16]:
df[df["category"].isin(["Market", "Clothing"])]

   order_id      city  category  quantity  unit_price           payment  total_price
1       202    Ankara  Clothing         2         900     Bank Transfer         1800
2       203  Istanbul    Market         5          90               EFT          450
4       205     Bursa    Market         3         150  Cash on Delivery          450

## 6. Sorting

In [17]:
df.sort_values("total_price", ascending=False)

   order_id      city     category  quantity  unit_price           payment  total_price
3       204     Izmir  Electronics         1       42000       Credit Card        42000
0       201  Istanbul  Electronics         1       15000       Credit Card        15000
1       202    Ankara     Clothing         2         900     Bank Transfer         1800
2       203  Istanbul       Market         5          90               EFT          450
4       205     Bursa       Market         3         150  Cash on Delivery          450

## 7. Quick Summaries: `value_counts` and `describe`

In [18]:
df["category"].value_counts()

category
Electronics    2
Market         2
Clothing       1
Name: count, dtype: int64

In [19]:
df[["quantity", "unit_price", "total_price"]].describe()

       quantity    unit_price   total_price
count   5.00000      5.000000      5.000000
mean    2.40000  11628.000000  11940.000000
std     1.67332  18123.111488  17887.334905
min     1.00000     90.000000    450.000000
25%     1.00000    150.000000    450.000000
50%     2.00000    900.000000   1800.000000
75%     3.00000  15000.000000  15000.000000
max     5.00000  42000.000000  42000.000000

## 8. Loading a Real CSV File

From here we work with a real sales dataset.  
Make sure `ybs_satis_verisi.csv` is in the same folder as this notebook.

In [20]:
sales = pd.read_csv("ybs_satis_verisi.csv")
sales.head()

,siparis_id,musteri_id,sehir,kategori,urun,adet,birim_fiyat,indirim_orani,satis_kanali,odeme_yontemi,siparis_tarihi,teslimat_gun,memnuniyet_puani,iptal_edildi
0,100001,1130,Adana,Kozmetik,Parfüm,3,2356.70,0.20,Web,Havale/EFT,2025-03-21,3,3,0
1,100002,1474,Kocaeli,Ev-Yaşam,Nevresim,4,11270.01,0.05,Mobil,Kredi Kartı,2025-03-31,3,1,0
2,100003,3435,Kocaeli,Market,Çay,4,584.78,0.10,Mobil,Kapıda Ödeme,2025-06-12,1,4,0
3,100004,1034,Konya,Elektronik,Powerbank,2,17651.03,0.05,Web,Kapıda Ödeme,2025-02-28,4,4,0
4,100005,5911,Ankara,Elektronik,Powerbank,4,14371.14,0.05,Mağaza,Kredi Kartı,2025-08-19,4,5,0

### 8.1 Data Type Check

In [21]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   siparis_id        300 non-null    int64
 1   musteri_id        300 non-null    int64
 2   sehir             300 non-null    str
 3   kategori          300 non-null    str
 4   urun              300 non-null    str
 5   adet              300 non-null    int64
 6   birim_fiyat       300 non-null    float64
 7   indirim_orani     300 non-null    float64
 8   satis_kanali      300 non-null    str
 9   odeme_yontemi     300 non-null    str
 10  siparis_tarihi    300 non-null    str
 11  teslimat_gun      300 non-null    int64
 12  memnuniyet_puani  300 non-null    int64
 13  iptal_edildi      300 non-null    int64
dtypes: float64(2), int64(6), str(6)
memory usage: 32.9 KB

### 8.2 Convert Order Date to datetime

In [22]:
sales["siparis_tarihi"] = pd.to_datetime(sales["siparis_tarihi"])
sales.dtypes

siparis_id                   int64
musteri_id                   int64
sehir                          str
kategori                       str
urun                           str
adet                         int64
birim_fiyat                float64
indirim_orani              float64
satis_kanali                   str
odeme_yontemi                  str
siparis_tarihi      datetime64[us]
teslimat_gun                 int64
memnuniyet_puani             int64
iptal_edildi                 int64
dtype: object

## 9. Select Only Relevant Columns

In [23]:
core = sales[["siparis_id", "sehir", "kategori", "urun", "adet", "birim_fiyat"]]
core.head()

   siparis_id    sehir    kategori       urun  adet  birim_fiyat
0      100001    Adana    Kozmetik     Parfüm     3      2356.70
1      100002  Kocaeli    Ev-Yaşam   Nevresim     4     11270.01
2      100003  Kocaeli      Market        Çay     4       584.78
3      100004    Konya  Elektronik  Powerbank     2     17651.03
4      100005   Ankara  Elektronik  Powerbank     4     14371.14

## 10. Real-World Filtering Scenarios

### 10.1 Electronics orders in Kocaeli

In [24]:
kocaeli_electronics = sales[
    (sales["sehir"] == "Kocaeli") & (sales["kategori"] == "Elektronik")
]
kocaeli_electronics.head()

,siparis_id,musteri_id,sehir,kategori,urun,adet,birim_fiyat,indirim_orani,satis_kanali,odeme_yontemi,siparis_tarihi,teslimat_gun,memnuniyet_puani,iptal_edildi
29,100030,4147,Kocaeli,Elektronik,Telefon,1,29878.78,0.20,Mobil,Kredi Kartı,2025-09-13,3,4,0
93,100094,2182,Kocaeli,Elektronik,Laptop,2,19268.44,0.20,Web,Banka Kartı,2025-07-16,3,4,0
98,100099,1010,Kocaeli,Elektronik,Kulaklık,4,10212.30,0.05,Web,Kredi Kartı,2025-11-11,3,5,1
135,100136,4553,Kocaeli,Elektronik,Kulaklık,5,35316.15,0.20,Mobil,Havale/EFT,2025-05-09,3,3,0
212,100213,4004,Kocaeli,Elektronik,Klavye,3,2495.98,0.10,Web,Banka Kartı,2025-03-12,2,5,0

### 10.2 Discount rate 15% and above

In [25]:
high_discount = sales[sales["indirim_orani"] >= 0.15]
high_discount.head()

,siparis_id,musteri_id,sehir,kategori,urun,adet,birim_fiyat,indirim_orani,satis_kanali,odeme_yontemi,siparis_tarihi,teslimat_gun,memnuniyet_puani,iptal_edildi
0,100001,1130,Adana,Kozmetik,Parfüm,3,2356.70,0.20,Web,Havale/EFT,2025-03-21,3,3,0
6,100007,4561,İstanbul,Ev-Yaşam,Tava,1,9294.27,0.15,Mobil,Havale/EFT,2025-05-11,4,5,0
9,100010,4314,Bursa,Market,Kahve,5,314.97,0.20,Mobil,Kredi Kartı,2025-04-24,2,5,0
10,100011,3038,Ankara,Kozmetik,Şampuan,5,943.25,0.20,Web,Kapıda Ödeme,2025-12-08,3,5,0
14,100015,1197,Bursa,Giyim,Elbise,2,5916.06,0.15,Web,Kapıda Ödeme,2025-02-22,4,4,0

### 10.3 Satisfaction score between 3 and 5 (inclusive)

In [27]:
satisfied = sales[sales["memnuniyet_puani"].between(3, 5)]
satisfied.head()

,siparis_id,musteri_id,sehir,kategori,urun,adet,birim_fiyat,indirim_orani,satis_kanali,odeme_yontemi,siparis_tarihi,teslimat_gun,memnuniyet_puani,iptal_edildi
0,100001,1130,Adana,Kozmetik,Parfüm,3,2356.70,0.20,Web,Havale/EFT,2025-03-21,3,3,0
2,100003,3435,Kocaeli,Market,Çay,4,584.78,0.10,Mobil,Kapıda Ödeme,2025-06-12,1,4,0
3,100004,1034,Konya,Elektronik,Powerbank,2,17651.03,0.05,Web,Kapıda Ödeme,2025-02-28,4,4,0
4,100005,5911,Ankara,Elektronik,Powerbank,4,14371.14,0.05,Mağaza,Kredi Kartı,2025-08-19,4,5,0
5,100006,3062,Konya,Kozmetik,Parfüm,5,1214.94,0.05,Web,Kapıda Ödeme,2025-08-08,2,4,0

### 10.4 Orders from the last 60 days

In [28]:
cutoff = sales["siparis_tarihi"].max() - pd.Timedelta(days=60)
recent = sales[sales["siparis_tarihi"] >= cutoff]
recent.head()

,siparis_id,musteri_id,sehir,kategori,urun,adet,birim_fiyat,indirim_orani,satis_kanali,odeme_yontemi,siparis_tarihi,teslimat_gun,memnuniyet_puani,iptal_edildi
10,100011,3038,Ankara,Kozmetik,Şampuan,5,943.25,0.20,Web,Kapıda Ödeme,2025-12-08,3,5,0
15,100016,3911,İstanbul,Market,Kahve,4,314.76,0.20,Mobil,Kapıda Ödeme,2025-12-03,1,4,0
18,100019,1098,Konya,Kozmetik,Diş Macunu,1,1954.73,0.10,Mobil,Kapıda Ödeme,2025-12-31,3,1,0
22,100023,3300,Konya,Ev-Yaşam,Termos,3,9002.90,0.20,Mobil,Kredi Kartı,2025-12-28,3,5,0
31,100032,3816,İstanbul,Ev-Yaşam,Süpürge,5,4854.24,0.05,Web,Kapıda Ödeme,2026-01-05,2,4,0

## 11. Sorting + Top 5 Most Expensive Orders

In [29]:
sales.sort_values("birim_fiyat", ascending=False).head(5)[
    ["siparis_id", "sehir", "kategori", "urun", "birim_fiyat", "adet"]
]

     siparis_id     sehir    kategori       urun  birim_fiyat  adet
269      100270   Kocaeli  Elektronik      Mouse     44979.70     3
256      100257     İzmir  Elektronik  Powerbank     44769.46     4
61       100062     İzmir  Elektronik     Laptop     44215.85     5
150      100151  İstanbul  Elektronik  Powerbank     44165.02     4
42       100043     Konya  Elektronik   Kulaklık     43363.40     5

## 12. Quick Dataset Overview

In [30]:
print("Total rows     :", len(sales))
print("Cities         :", sales["sehir"].unique())
print("Categories     :", sales["kategori"].unique())
print("Cancelled (%)  :", round(sales["iptal_edildi"].mean() * 100, 1))

Total rows     : 300
Cities         : <StringArray>
['Adana', 'Kocaeli', 'Konya', 'Ankara', 'İstanbul', 'Bursa', 'Antalya', 'İzmir']
Length: 8, dtype: str
Categories     : <StringArray>
['Kozmetik', 'Ev-Yaşam', 'Market', 'Elektronik', 'Giyim']
Length: 5, dtype: str
Cancelled (%)  : 6.3